---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: sonic-eats-ms

outputs:
  - name: build-output

run:
  path: bash
  args: [./sonic-eats-ms/build.sh]
