groups: []
resources:
- name: deploy-ms
  type: cf
  source:
    api: https://api.sys.pcf-bootcamp.techolution.com
    organization: sonic-bootcamp
    password: ******
    skip_cert_check: false
    space: bootcamp9
    username: bootcamp9
- name: sonic-eats-ms
  type: git
  source:
    branch: Build-Passed
    check_every: 30s
    trigger: true
    uri: https://github.com/BoomerBrian/sonic-eats-ms.git
- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
jobs:
- name: build/run-tests
  public: true
  serial: true
  plan:
  - get: sonic-eats-ms
    trigger: true
  - task: build
    file: sonic-eats-ms/build.yml
    on_failure:
      put: slack-alert
      params:
        channel: '#hackathon-winners'
        text: Failed Deploy
    on_success:
      put: slack-alert
      params:
        channel: '#hackathon-winners'
        text: Successful Deploy
  - put: deploy-ms
    params:
      manifest: sonic-eats-ms/manifest.yml
      path: build-output/demo-service-0.0.1-SNAPSHOT.jar
